name: Bug report
description: Create a bug report for something that is not working as expected
title: "Bug: "
labels:
  - bug
  - needs-triage
assignees:
  - klejejs

body:
  - type: textarea
    id: issue
    validations:
      required: true
    attributes:
      label: Issue
      description: A clear and concise description of what the bug is.

  - type: textarea
    id: expected_behavior
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: debug_file_data
    validations:
      required: true
    attributes:
      label: Debug File Data
      description: Please attach Thermia debug file data that can help diagnose the issue. To get the debug file data, see [README.md](https://github.com/klejejs/python-thermia-online-api?tab=readme-ov-file#regarding-unsupported-models).

  - type: textarea
    id: screenshots_from_ui
    attributes:
      label: Screenshots from Thermia Online web interface
      description: If possible/applicable, please add screenshots from the Thermia Online web interface showing how the sensor/switch is displayed there.

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Please check the following before opening a new issue
      options:
        - label: I have checked and am running the latest version of the package
          required: true
        - label: I have checked and the issue I am reporting is not listed under the [common issues section in README.md](https://github.com/klejejs/python-thermia-online-api/tree/main?tab=readme-ov-file#common-issues), or the fix listed there does not work
          required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Add additional context here
