name: Bug report
description: Create a bug report for something that is not working as expected
title: "Bug: "
labels:
  - bug
  - needs-triage
assignees:
  - klejejs

body:
  - type: markdown
    attributes:
      value: |
        **Describe the issue**
        A clear and concise description of what the bug is.

  - type: textarea
    id: issue
    validations:
      required: true
    attributes:
      label: Issue
      description: A clear and concise description of what the bug is.

  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expected to happen.

  - type: textarea
    id: expected_behavior
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: markdown
    attributes:
      value: |
        **Debug file data**
        Please attach Thermia debug file data that can help diagnose the issue. To get the debug file data, see [README.md](https://github.com/klejejs/python-thermia-online-api?tab=readme-ov-file#regarding-unsupported-models).

  - type: textarea
    id: debug_file_data
    validations:
      required: true
    attributes:
      label: Debug File Data
      description: Please attach Thermia debug file data that can help diagnose the issue.

  - type: markdown
    attributes:
      value: |
        **Are you running the latest version?**
        Please check if you are running the latest version of the package before submitting a bug report.

  - type: checkboxes
    id: latest_version
    attributes:
      label: Are you running the latest version?
      description: Please check if you are running the latest version of the package before submitting a bug report.
      options:
        - label: I have checked and am running the latest version of the package
          required: true

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context about the problem here.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Add additional context here
